import sys
import os
import inspect
from typing import Type, List
from pydantic import BaseModel

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from database.models import Signal, Trade, RiskReview, MarketTrend, APICallLog, AgentEvent
from strategy.technical import TechIndicators
from strategy.correlations import StockRelation, CrossImpact
from agent_config import AgentSettings

OUTPUT_FILE = "docs/api-reference.md"

def generate_model_markdown(model: Type[BaseModel], title: str) -> str:
    schema = model.model_json_schema()
    props = schema.get("properties", {})
    
    md = [f"### {title}\n"]
    if schema.get("description"):
        md.append(f"{schema['description']}\n")
        
    md.append("| Field | Type | Description | Default |")
    md.append("|-------|------|-------------|---------|")
    
    for name, info in props.items():
        field_type = info.get("type", "any")
        if "anyOf" in info:
            types = [t.get("type", "null") for t in info["anyOf"]]
            field_type = " / ".join(filter(lambda x: x != "null", types))
            if "null" in types:
                field_type += "?"
        
        desc = info.get("description", "").replace("\n", " ")
        default = info.get("default", "-")
        if default == "-":
            # Check required
            if name in schema.get("required", []):
                default = "**Required**"
            else:
                default = "None"
                
        md.append(f"| `{name}` | `{field_type}` | {desc} | {default} |")
    
    md.append("\n")
    return "\n".join(md)

def main():
    content = [
        "# 📚 API Reference",
        "\n> **Note:** This file is auto-generated by `docs/generate_api_reference.py`.",
        "\n## Core Data Models\n",
    ]
    
    models_to_doc = [
        (Signal, "Signal"),
        (Trade, "Trade"),
        (RiskReview, "RiskReview (Devil's Advocate)"),
        (MarketTrend, "MarketTrend"),
        (APICallLog, "APICallLog"),
        (AgentEvent, "AgentEvent"),
    ]
    
    for model, title in models_to_doc:
        content.append(generate_model_markdown(model, title))
        
    content.append("## Auxiliary Models\n")
    aux_models = [
        (TechIndicators, "TechIndicators"),
        (StockRelation, "StockRelation"),
        (CrossImpact, "CrossImpact"),
    ]
    
    for model, title in aux_models:
        content.append(generate_model_markdown(model, title))

    content.append("## Configuration\n")
    content.append(generate_model_markdown(AgentSettings, "AgentSettings (.env)"))
    
    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(content))
    
    print(f"✅ Generated API Reference at {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
